/panda/controller_manager:
  ros__parameters:
    update_rate: 1000  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cartesian_velocity_controller:
      type: my_simple_controllers/CartesianVelocityController

/panda/cartesian_velocity_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    command_topic: /panda/cartesian_velocity_controller/commands
    command_timeout: 100.0
    kp: [50.0, 50.0, 50.0, 30.0, 30.0, 30.0]
